name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Publish Project
        run: dotnet publish Frontend.csproj -c Release -o release --nologo

      - name: Create .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: release/wwwroot
